import type { CapabilitySkill } from '../index.ts';
export const mediaRuntimeSkillId = 'system-media-runtime';
export const mediaRuntimeSkill = Object.freeze({
  id: mediaRuntimeSkillId, title: 'Media Runtime',
  summary: `<system_skill id="${mediaRuntimeSkillId}">Inspect media before expensive processing, use bounded frame/OCR/transcription scopes, and label generated versus source media accurately.</system_skill>`,
  content: `# Media Runtime

- Inspect the source before choosing OCR, transcription, or frame extraction. Use the smallest adequate page, time, language, and frame scope. Preserve timestamps and source references. OCR/transcription are probabilistic; flag uncertain names, numbers and inaudible text.
- Use listModels to discover built-in and configured image, video, and speech models AND local composition capabilities. models lists generative models; capabilities.composeVideo describes the separate local Remotion renderer, its supported scene types, animation scope and render budget. No video model in models does NOT mean video composition is unavailable. Never probe generateSpeech or generateVideo when the corresponding model kind is absent. modelRef is the returned configuration id; omit it to use the selected model of that type. Host-selected models are independent of the language model and take precedence over modelRef. The built-in Codex CLI image model uses local login and requires no API configuration; it supports reference images but not masks. Never invent model ids or API endpoints.
- generateImage accepts prompt, optional sourceRefs and maskRef for editing, size and count. generateVideo accepts prompt, at most one starting image in sourceRefs, duration, size and aspectRatio. generateSpeech converts exact prompt text into speech with optional voice, language and outputFormat; it does not generate music or sound effects.
- For a complete image-based video, use the built-in Remotion composeVideo workflow. Draft a timed script, generate scene images (reuse reference images for visual consistency), generateSpeech only if a speech model is configured, then composeVideo with scenes=[{sourceRef: exact saved image URL, duration: seconds, motion: 'zoomIn', caption: 'optional on-screen text'}, ...], optional audioRef and size (default 1280x720, even dimensions 128..1920). Remotion renders a complete H.264 MP4 at 30fps with animated camera movement, captions and synchronized audio. motion is none, zoomIn, zoomOut, panLeft or panRight. This animates images; do not claim it synthesizes character motion. Use multiple timed caption scenes if narration is long. Up to 60 scenes and 600 seconds total; a requested 2-minute movie must total 120 seconds. Images fit inside the frame. Inspect narration duration and align scenes before rendering. No video model or model API key is required for composition. Do not switch to generateVideo merely because the user says 'complete video, not storyboard images'. Do not use terminal/codeSandbox to implement a separate FFmpeg pipeline. Return the actual MP4 URL and editable project.
- Remotion is the renderer, not a promise of arbitrary animation support in this tool. This integration currently accepts image/video scenes and moves the whole frame; it cannot author custom React/SVG compositions, rig characters or animate their limbs. A hand-drawn image with a camera pan is not character animation. Disclose this gap before promising animated-character work; do not claim motion from the still-image prompt alone.
- A requested complete movie must be delivered as one playable final file of the requested duration. Intermediate segments and test renders are working artifacts, not a completed movie. If segments are needed, compose them into the final file before delivery. Do not silently shorten the requested duration, lower resolution or hand off assembly to the user to work around a timeout. Report unresolved rendering failures accurately. The renderer has a separate configured deadline; a failure near a generic two-minute tool deadline does not establish Remotion's maximum movie length. Avoid repeated benchmark renders or searching/modifying host application source to infer tool capabilities; use listModels and the returned errors.
- Remotion does not synthesize speech. When no speech model is available, finish independent image/script work, then explain the missing narration capability and use requestUserInput for the user to configure a speech model, supply an audio file, or choose captions-only. Do not repeatedly call an unavailable speech tool, claim a silent video has narration, or abandon the whole task after a recoverable tool failure. A tool failure is evidence for the next model step, not completion of the user's request.
- composeVideo also accepts scenes with kind=video, trimStart (source seconds) and muted (original audio). Use inspect first and keep trimStart+duration inside the source. Audio edits use audioOffset (start on timeline), audioTrimStart (source start), audioDuration and audioVolume (0..1). Narration replaces the clips' original audio; without it, unmuted video clips retain their sound. Export is frame-aligned at 30fps. The chat host saves an editable project with its source assets, motion and captions. The in-chat editor uses the same Remotion composition for preview and export. The user can replace/add scenes, split, trim, reorder, edit captions/motion and adjust narration, then save and export a new MP4. Export does not overwrite the original video. An imported flattened video is editable as a video clip; it cannot recover original layers or separate baked-in music/voice.
- Reference inputs must be registered attachment ids or artifact URLs. Credentials and service paths belong to host settings, never tool arguments.
- Video generation waits for completion. Do not resubmit a timed-out generation automatically: the remote job may still run.
- Generated media is ALREADY saved by the host. Do not download it again with file.download, browser fetch or codeSandbox. For PPT/Word/PDF use, the file tool automatically mounts saved media as document assets. file plan/list returns availableAssets: match artifactId to ref and use the exact assetName. To add new images to an existing draft, list assets and edit the SAME draft; do not regenerate it.
- Clearly label generated media; never present it as source evidence. Actions return each saved file once in data. Use the exact url for Markdown images/inline media and downloadUrl for download links. These are delivery URLs, not instructions to download into a workspace. Copy them verbatim: a leading slash is application-relative, not a hostname. Never add a scheme, invent a domain, or invent attachment://, sandbox:, file: or filesystem URLs.`,
  required: true, activation: [{ toolName: 'media', actions: ['listModels', 'inspect', 'extractFrames', 'ocr', 'transcribe', 'generateImage', 'generateVideo', 'generateSpeech', 'composeVideo'] }],
} satisfies CapabilitySkill);
